### PR TITLE
Fix walk over rocks

### LINKED ISSUE #63: Can't walk over destroyed wall
When a bomb explodes and takes out a wall, the player should be able to walk where the wall was.

### PR DESCRIPTION
**Pull request by JacopoG**
Closes #63.

### CODE REVIEW

**Review by eldarht — APPROVED** [review]

File: core/src/no/group15/playmagic/ecs/GameMap.kt [hunk 1]
```diff
@@ -56,6 +56,14 @@ class GameMap {
 	}
 
 
+
+	fun setEmptyTile(x: Float, y: Float) {
+		val x = toMatrixCoordX(x)
+		val y = toMatrixCoordY(y)
+		mapMatrix[y][x] = TileType.EMPTY
```
Comment (DeimosA) [inline core/src/no/group15/playmagic/ecs/GameMap.kt]: It would be nice if this was resettable without making a new instance of the class
Maybe with a destroyed rock type that would be treated as empty, but there could then be a resetMap function that iterates over the map and sets this back to a rock type

also you might want to check that there is a rock there before setting it destroyed

File: core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt [hunk 2]
```diff
@@ -116,4 +120,14 @@ class MovementSystem(
 		}
 	}
 
+
+	override fun receive(signal: Signal<CollisionEvent>, event: CollisionEvent) {
+		val destructible = mapperFor<DestructibleComponent>()
+		val rock = if (event.entity1.has(destructible)) event.entity1 else event.entity2
+		val rockPosition = rock[transformMapper]!!.position
```
Comment (DeimosA) [inline core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: these should be the opposite `transformMapper[rock].position`
always `mapper[entity]`

File: core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt [hunk 3]
```diff
@@ -116,4 +120,14 @@ class MovementSystem(
 		}
 	}
 
+
+	override fun receive(signal: Signal<CollisionEvent>, event: CollisionEvent) {
```
Comment (DeimosA) [inline core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: Is this related to movement? maybe bomb system or entity management

**Review by DeimosA — CHANGES_REQUESTED** [review]

File: core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt (hunk 2 above)
Comment (JacopoG) [reply core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: Do you mean as best practice? Because also that syntax  work thanks to KTX

Comment (DeimosA) [reply core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: yes, and you don't have to use all the exclamation marks
I've changed these in master

Comment (DeimosA) [reply core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: It's like you're looking up something in a map, I just think it makes more sense that way 😄

Comment (JacopoG) [reply core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: make sense. I seen that syntax in KTX and I just started using it, I liked it because if you call the mapper `transform` you can access to the component with this syntax `entity[transform]` (it is cool). But the fact you have to use the double exclamation mark does it make all horrible. I agree with you at the end :+1:

File: core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt (hunk 3 above)
Comment (JacopoG) [reply core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: I put this code here because I need to access the gameMap :grin:

File: core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt (hunk 2 above)
Comment (DeimosA) [reply core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: but calling the mapper transform is very confusing, it should be named for what it is; a transformMapper. transform is what the mapper returns.
player is even worse 😄 
`val player = player[player]!!`
like what is what

File: core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt (hunk 3 above)
Comment (DeimosA) [reply core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: It is also in EntityManagementSystem, at least in master

File: core/src/no/group15/playmagic/ecs/GameMap.kt (hunk 1 above)
Comment (JacopoG) [reply core/src/no/group15/playmagic/ecs/GameMap.kt]: Done!

File: core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt (hunk 3 above)
Comment (JacopoG) [reply core/src/no/group15/playmagic/ecs/systems/MovementSystem.kt]: Moved to EntityManagementSystem.

**Comment by JacopoG** [comment]
@DeimosA check the new commits!

**Comment by DeimosA** [comment]
nice
